name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-on-macos:
    strategy:
      matrix:
        xcode-version: ['16.3']
    runs-on: macos-15
    timeout-minutes: 3
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode-version }}.app
    steps:
      - uses: actions/checkout@v4
      - name: Run swift build
        run: swift build
      - name: Run swift test
        run: swift test

  test-on-linux:
    strategy:
      matrix:
        swift-version: ['6.1', '6.0', '5.10', '5.9', '5.8']
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: apt-get -y install libcurl4-openssl-dev
      - name: Install Swiftly
        run: >
          curl -O https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz &&
          tar zxf swiftly-$(uname -m).tar.gz &&
          ./swiftly init --skip-install --quiet-shell-followup &&
          . ~/.local/share/swiftly/env.sh &&
          hash -r
      - name: Install Swift ${{ matrix.swift-version }}
        run: |
          swiftly install --use ${{ matrix.swift-version }}
          swift --version
      - name: Run swift build
        run: swift build
      - name: Run swift test
        run: swift test
