name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-on-macos:
    strategy:
      matrix:
        xcode-version: ['16.1', '15.4', '15.2']
    runs-on: macos-14
    timeout-minutes: 3
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode-version }}.app
    steps:
      - uses: actions/checkout@v4
      - name: Run swift build
        run: swift build
      - name: Run swift test
        run: swift test

  test-on-linux:
    strategy:
      matrix:
        swift-version: ['6.0', '5.10', '5.9', '5.8']
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - name: Install Swift ${{ matrix.swift-version }}
        run: |
          curl -L https://swiftlang.github.io/swiftly/swiftly-install.sh | bash -s -- -y
          swiftly install ${{ matrix.swift-version }}
      - name: Run swift --version
        run: swift --version
      - name: Run swift build
        run: swift build
      - name: Run swift test
        run: swift test
