name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-on-macos:
    strategy:
      matrix:
        xcode-version: ['16.4', '16.2']
    runs-on: macos-15
    timeout-minutes: 3
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode-version }}.app
    steps:
      - uses: actions/checkout@v4
      - name: Run swift test
        run: swift test

  test-on-linux:
    strategy:
      matrix:
        swift-version: ['6.1', '6.0']
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libcurl4-openssl-dev
      - name: Install Swift ${{ matrix.swift-version }}
        run: >
          curl -O https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz &&
          tar zxf swiftly-$(uname -m).tar.gz &&
          ./swiftly init --assume-yes --skip-install &&
          . ~/.local/share/swiftly/env.sh &&
          swiftly list-available &&
          swiftly install --use ${{ matrix.swift-version }} &&
          swift --version
      - name: Run swift test
        run: |
          . ~/.local/share/swiftly/env.sh
          swift test
